---

is_debug: true
directories:
  - path:
    commands:
      - go run ./build/bin/app2
      - go run ./build/bin/app1
    include_regexp:
      - .*.go$
      - .*.env$
    exclude_regexp:
      - .*._test.go$
    log_file: path1.log

  - path: D:\prolog
    commands:
      - echo Ivan Startsev
    include_regexp:
      - .*.go$
      - .*.env$
    exclude_regexp:
      - .*._test.go$
    log_file: path2.log

storage:
  host: localhost
  port: 5432
  database:
  username:
  password:
